#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-@Digest@
spec:
  serviceAccountName: event-listener
  triggers:
  - bindings:
    - apiversion: v1alpha1
      name: build-push-promote-pl-@Digest@-push-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "push" && body["webhooks-tekton-git-branch"] == "master"'
    name: kabanero-push-event
    template:
      apiversion: v1alpha1
      name: build-push-promote-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: build-pl-@Digest@-pullrequest-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "pull_request" && body["webhooks-tekton-git-branch"] != "master" && (body["action"] == "opened" || body["action"] == "synchronize" ) '
    name: kabanero-pullrequest-event
    template:
      apiversion: v1alpha1
      name: build-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: image-retag-pl-@Digest@-push-binding
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "tag" '
    name: kabanero-tag-event
    template:
      apiversion: v1alpha1
      name: image-retag-pl-@Digest@-template
  - bindings:
    - apiversion: v1alpha1
      name: monitor-task-@Digest@-github-binding
    template:
     apiversion: v1alpha1
     name: monitor-task-@Digest@-template
    name: kabanero-monitor-task-event
    interceptors:
    - cel:
        filter: 'body["webhooks-tekton-event-type"] == "pull_request" && body["webhooks-tekton-git-branch"] != "master" && (body["action"] == "opened" || body["action"] == "synchronize" ) '
