#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: monitor-task-@Digest@-github-binding
spec:
  params:
  - name: pullrequesturl
    value: $(body.pull_request.html_url)
  - name: statusesurl
    value: $(body.pull_request.statuses_url)
  - name: webhooks-tekton-service-account
    value: $(body.webhooks-tekton-service-account)
  - name: gitsecretname
    value: $(body.webhooks-tekton-github-secret-name)
  - name: gitsecretkeyname
    value: $(body.webhooks-tekton-github-secret-key-name)
  - name: dashboardurl
    value: $(body.webhooks-tekton-monitor-dashboard-url)
  - name: insecure-skip-tls-verify
    value: $(body.webhooks-tekton-insecure-skip-tls-verify)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: monitor-task-@Digest@-gitlab-binding
spec:
  params:
  - name: pullrequesturl
    value: $(body.object_attributes.url)
  - name: statusesurl
    value: projects/$(body.project.id)/statuses/$(body.object_attributes.last_commit.id)
  - name: webhooks-tekton-service-account
    value: $(body.webhooks-tekton-service-account)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: monitor-task-@Digest@-template
spec:
  params:
  - name: pullrequesturl
    description: The pull request url
    type: string
  - name: statusesurl
    description: The statuses url
    type: string
  - name: gitsecretname
    description: The git secret name
    default: github-secrets
    type: string
  - name: gitsecretkeyname
    description: The git secret key name
    default: token
    type: string
  - name: commentsuccess
    description: The text of the success comment
    default: "Success"
    type: string
  - name: commentfailure
    description: The text of the failure comment
    default: "Failed"
    type: string
  - name: commenttimeout
    description: The text of the timeout comment
    default: "Unknown"
    type: string
  - name: commentmissing
    description: The text of the missing comment
    default: "Missing"
    type: string
  - name: dashboardurl
    description: The URL to the pipelineruns page of the dashboard
    default: "http://localhost:9097/"
    type: string
  - name: provider
    description: The git provider, "github" or "gitlab"
    default: "github"
    type: string
  - name: apiurl
    description: The git api URL for the repository
    default: ""
    type: string
  - name: insecure-skip-tls-verify
    description: Whether or not to skip SSL validation of certificates ("true" or "false")
    default: "false"
    type: string
  - name: webhooks-tekton-service-account
    description: Service account to run 
    type: string
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: pull-request-$(uid)
    spec:
      type: pullRequest
      params:
        - name: url
          value: $(params.pullrequesturl)
        - name: insecure-skip-tls-verify
          value: $(params.insecure-skip-tls-verify)
      secrets:
        - fieldName: authToken
          secretName: $(params.gitsecretname)
          secretKey: $(params.gitsecretkeyname)
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: monitor-task-@Digest@-taskrun-
    spec:
      serviceAccountName: $(params.webhooks-tekton-service-account)
      taskRef:
        name: monitor-task-@Digest@
      params:
        - name: commentsuccess
          value: $(params.commentsuccess)
        - name: commentfailure
          value: $(params.commentfailure)
        - name: commenttimeout
          value: $(params.commenttimeout)
        - name: dashboard-url
          value: $(params.dashboardurl)
        - name: secret
          value: $(params.gitsecretname)
        - name: secretkey
          value: $(params.gitsecretkeyname)
        - name: statusesurl
          value: $(params.statusesurl)
        - name: provider
          value: $(params.provider)
        - name: apiurl
          value: $(params.apiurl)
        - name: insecure-skip-tls-verify
          value: $(params.insecure-skip-tls-verify)
      resources:
        inputs:
          - name: pull-request
            resourceRef:
              name: pull-request-$(uid)
        outputs:
          - name: pull-request
            resourceRef:
              name: pull-request-$(uid)
