apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kabanero-cache
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
