apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-image
  spec:
    params:
    - name: url
      value: <image registry like docker.io/foo> 
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-source
  spec:
    params:
    - name: revision
      value: master
    - name: url
      value: <https://github.com/userID/RepoName>
    type: git
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-source-gitops
  spec:
    params:
    - name: revision
      value: master
    - name: url
      value: <https://github.com/userID/GitOpsRepoName>
    type: git
kind: List
