apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: <stack-name>-image-retag-push-manual-pipeline-run
spec:
  serviceAccount: kabanero-operator
  timeout: "1h0m0s"
  pipelineRef:
    name: <stack-name>-image-retag-push-pipeline
  resources:
    - name: docker-src-image
      resourceRef:
        name: docker-src-image
    - name: docker-dest-image
      resourceRef:
        name: docker-dest-image
